### ISSUE TITLE
django.db.utils.IntegrityError: UNIQUE constraint failed

### ISSUE THREAD

**Issue by agusmakmun** [mauricioabreu/clonery#1]
```python
class Post(TimeStampedModel):
    author = models.ForeignKey(User, related_name='posts',
                               on_delete=models.CASCADE)
    title = models.CharField(_('Title'), max_length=200)
    content = models.TextField(_('Content'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
```

```python
if field.many_to_one:
    related_instance = getattr(instance, field.name)
    related_instance.pk = None
    related_instance.id = None
    related_instance.save()   # got an error
```

This showed me an error;

```python
>>> from app.models import Post
>>> from app.utils import  clone
>>> 
>>> post = Post.objects.first()
>>> 
>>> clone(post)
Traceback (most recent call last):
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/agus/envs/env-django-cloner/django-object-cloner/object_cloner_demo/app/utils.py", line 22, in clone
    related_instance.save()
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/agus/envs/env-django-cloner/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
>>> 
```

**Comment by mauricioabreu** [comment]
Thank you for reporting this error. I'll try to investigate it today.

**Comment by agusmakmun** [comment]
@mauricioabreu thanks buddy, previously I also asked this similar issue here https://stackoverflow.com/questions/61584535/django-clone-the-recursive-objects

> I see this plugin will be very useful in the future, for example in e-commerce system when you want to clone the `Product` object along with their children like `ProductInfo`, `ProductAttribute`, `ProductImages`, etc.

**Comment by mauricioabreu** [comment]
I think `clonery` is trying to clone the User object but it has a constraint. Right?

**Comment by mauricioabreu** [comment]
If so, I will need to provide a way to exclude some objects to be cloned.
